# Read the Docs configuration file
# Version 2 recommended
version: 2

# Build settings
build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Python dependencies
python:
  install:
    - method: pip
      path: .

# Optionally, specify requirements file
# python:
#   install:
#     - requirements: docs/requirements.txt
